### ISSUE TITLE
Проблема чтении и записи перевода

### ISSUE THREAD

**Issue by VacaVasa** [dfint/installer#101]
На данный момент программа не может определять строки с переносом, из-за чего большинство интерфейса не переведено.
Хоть я и не силен в питоне, я посмотрел основной скрипт. Насколько мне известно, строки считываются нормально, но в них присутствует перенос строки, а в dictionary.csv текст записано всё всего в одну строку, поэтому не изменив формат записи я не представляю как иначе можно решить эту проблему.
Думаю если к примеру сделать чтение всех строчек до знака ";", они будут содержать знак переноса строки и будут соответствовать значению строки из игры и перевод будет работать.

**Comment by insolor** [comment]
@VacaVasa сейчас никакие скрипты на питоне не используются. Перевод выполняется с помощью https://github.com/dfint/df-steam-hook-rs. В исходных строках изначально нет никаких переносов, они появляются только когда текст выводится в "окошках".

**Comment by insolor** [comment]
Duplicate of #99
