### ISSUE TITLE
Событие 1000 , Application Error

### ISSUE THREAD

**Issue by PurpleSnowFall** [dfint/installer#102]
При  установки файла руссфикатора и дальнейшем запуске игры , Windows 11 в журнал событий спамит ошибку :

Имя сбойного приложения: Dwarf Fortress.exe, версия: 0.0.0.0, метка времени: 0x66d87e02
Имя сбойного модуля: dfhooks_dfint.dll_unloaded, версия: 0.0.0.0, метка времени: 0x65f34fcf
Код исключения: 0xc0000005
Смещение ошибки: 0x000000000000527c
Идентификатор сбойного процесса: 0x0x432C
Время запуска сбойного приложения: 0x0x1DB2653C13F2F19
Путь сбойного приложения: E:\SteamLibrary\steamapps\common\Dwarf Fortress\Dwarf Fortress.exe
Путь сбойного модуля: dfhooks_dfint.dll
Идентификатор отчета: 7dd75dbb-463b-4840-b739-421be6333506
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

Ошибка исчезает при проверке файлов игры в Steam , он заменяет файл " dfhooks_dfint.dll " и в игре иероглифы

**Comment by insolor** [comment]
Если используете антивирус - пробуйте его отключать или добавлять папку с игрой в исключения.

Steam не должен никак влиять на dfhooks_dfint.dll, этот файл устанавливает русификатор, стим или DF про него ничего не знает.

Если иероглифы - пробуйте в инсталлере опять прожимать "Обновить", файл шрифта должен замениться.

**Comment by insolor** [comment]
Один "поврежденный" файл - это файл шрифта, из-за отката на стандартный файл кириллица выводится иероглифами. На ошибку журнале событий это никак не должно влиять. Пока могу посоветовать разве что игнорировать ошибки, если это никак не влияет на игру.
