### ISSUE TITLE
Linux server translation setup

### ISSUE THREAD

**Issue by Audifl0** [dfint/installer#121]
Hello,

I don't know where to put my problem. So I'll do it here.
I have installed dwarf fortress on a linux server in order to play it in co-op with a friend. I'd also like to install the French translation. But I can't find a way to install it on a server, as the installer requires a graphical interface.

Thank you for your help,

**Comment by insolor** [comment]
You can build/download a ready to use package from the [package builder](https://dfint-package-build.streamlit.app), then just unpack it to the game's directory with file replacement.

But you'll still need a graphical interface to play.
