### ISSUE TITLE
Justice screen displays with error

### ISSUE THREAD

**Issue by ariukeera** [dfint/installer#40]
![jvOY6bHP8Vw](https://github.com/dfint/installer/assets/67847344/5daa5200-9eab-49e2-9cc6-9b1cf86dd2e8)

**Comment by shevernitskiy** [comment]
@ariukeera It is DF issue.

**Comment by insolor** [comment]
Investigating

**Comment by insolor** [comment]
Problematic string found:

![photo_2024-05-02_15-07-11](https://github.com/dfint/installer/assets/2442833/a4a17dfa-1ab7-49f8-8a30-55172996b068)

Translation removed globally for all languages.

Please, update the dictionary in the installer.
