### ISSUE TITLE
Nobles & administrators

### ISSUE THREAD

**Issue by Xilleet** [dfint/installer#43]
Крякозябры в меню Nobles & administrators

![Dwarf_Fortress_sv9Zd4KkCc](https://github.com/dfint/installer/assets/168185634/a54adbe5-500b-446a-b172-6346b495ef3a)

**Comment by insolor** [comment]
Нужно переключить словарь на "Русский (cp1251)". Сейчас по умолчанию кодировка словаря и шрифта cp866, раньше была cp1251.
