### ISSUE TITLE
There is no Chinese option in the dropdown menu

### ISSUE THREAD

**Issue by AllenLmz** [dfint/installer#57]
How can I add a new language? I see that there is already a Chinese translation here

https://explore.transifex.com/dwarf-fortress-translation/dwarf-fortress-steam/

**Comment by insolor** [comment]
@AllenLmz at the moment, the game itself doesn't support output of text with a hieroglyphic script. See the explanation here: https://github.com/dfint/df-steam-hook#supported-languages

**Comment by insolor** [comment]
Duplicate of #32
