### ISSUE TITLE
The "View a detailed description of this activity" button does not work

### ISSUE THREAD

**Issue by dimadetroit** [dfint/installer#64]
Hi
Dwarf Fortress v50.13
When using a localisation, when one of the dwarves in a tavern listens to a story, a song, communicates, and it becomes possible to read what he is communicating about, the button with the image of a magnifying glass does not press.
Without a localisation, the activity works normally
Hook version 757258397
Dictionary Russian 3697479881
Using dfint installer, release 0.4.0 from https://github.com/dfint/installer/releases/tag/0.4.0
![Screenshot_396](https://github.com/dfint/installer/assets/57590355/84cf6a06-faa6-4379-8f48-c6c969b691ba)

**Comment by insolor** [comment]
We need the save to reproduce the problem.

**Comment by dimadetroit** [comment]
> We need the save to reproduce the problem.

Yeah, sure, 
The save folder weighs 85 MB, the save file is about 50 MB, so I’m attaching a download link:
https://drive.google.com/file/d/1Uypq3yqWVrZfR1zgod6HyldGxWzEwslc/view?usp=drive_link

**Comment by insolor** [comment]
Should be fixed now (by removing the translation of "Citizens" string). Please update the dictionary.
