### ISSUE TITLE
hook and dictionary not loading

### ISSUE THREAD

**Issue by daxime** [dfint/installer#81]
Hi,
I am on Manjaro (up to date), and the installer (v0.4.3 and v0.4.4) just don't work for me. It just say "hook data was not loaded" same for dictionary.

I tried launch it with command line to have more info, but there are no output in the terminal.
![Capture d’écran du 2024-08-24 04-24-52](https://github.com/user-attachments/assets/4376858f-d583-4c12-9e88-29235ad916b8)

**Comment by insolor** [comment]
The installer loads data to install or update the localization from the https://github.com/dfint/update_data repository. Check that your firewall doesn't block requests of the installer to the internet.

**Comment by daxime** [comment]
I don't use a firewall. I checked if it's enabled by default, but it's not. I guess my connection is bad, it happens from time to time. I'll try it later with a different connection.

**Comment by insolor** [comment]
@daxime you can use the [package builder](https://dfint-package-build.streamlit.app), it creates a ready to use standalone package.

As for encoding, [autobuild](https://github.com/dfint/autobuild) currently creates csv files in cp859. To use a different encoding you will have to create the csv file yourself, and then add a font file corresponding to the encoding you choose.

**Comment by daxime** [comment]
Thx for the builder.
My problem was my connection...
