### ISSUE TITLE
инсталятор и сборщик пакетов не работают

### ISSUE THREAD

**Issue by fhjndhb** [dfint/installer#90]
инсталятор и сборщик пакетов не работают. перевода игры нет! сделала все по инструкции

**Comment by insolor** [comment]
@fhjndhb по этой информации могу предположить подобную проблему: https://vk.com/topic-50714193_28829017?post=1755

Пробуйте запускать от администратора, возможно будет достаточно один раз запустить от администратора.

**Comment by insolor** [comment]
Т.к. никакого ответа нет, будем считать, что проблема решилась
